services:
  ollama:
    container_name: ollama
    build: 
      context: .
      dockerfile: DockerfileOllama
    ports:
      - "11434:11434"
  voice:
    container_name: voice
    image: "valkyrie1/deployment:latest"
    ports:
      - "8000:8000"