services:
  ollama:
    container_name: ollama
    build: 
      context: ../
      dockerfile: ./Docker/DockerfileOllama
    ports:
      - "8000:11434"
  short_news:
    container_name: app
    depends_on:
      - ollama
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    environment:
      - ollama_api=http://ollama:11434
    ports:
      - "8002:8080"
